/* GENERATED by scripts/make-lock-logo.py -- do not edit by hand.

   The mark a locked handset draws, and the version that tells it when to fetch a new one.
   Generated rather than typed so the version can never name bytes it does not match: a
   stale version is a phone showing last month's logo for ever, with nothing on any screen
   to say so.

   The path is RELATIVE. The handset resolves it against the server it was provisioned
   against, so the same APK serves HOPE and Hoop and each fetches its own mark. */
export const LOCK_LOGO = { path: '/lock-logo.png', version: 'b81be484' };
