/* THE SAME LINE, FOR THE SAME REASON. Not optional -- see RUN-ME-001's own note on this. */
set search_path = hopeloan, public;

/* =====================================================================================
   1. BUSINESS VERIFICATION -- THREE NAMED PHOTOS, NOT ONE.
   =====================================================================================
   "3 business verification photos (customer alone / customer+officer / customer+officer+
   guarantor)" -- the existing business_verify_photo_url (RUN-ME-004) becomes the first of
   the three rather than being replaced, so nothing already captured is orphaned. */
alter table customers add column if not exists business_verify_photo2_url text;   -- customer + officer
alter table customers add column if not exists business_verify_photo3_url text;   -- customer + officer + guarantor

/* =====================================================================================
   2. RESIDENCE VERIFICATION -- FOUR PHOTOS EACH, CUSTOMER AND GUARANTOR.
   =====================================================================================
   "4 residence photos each for customer and guarantor" -- same treatment: the existing
   single photo (RUN-ME-004) becomes photo 1 of 4 for each of the two people. */
alter table customers add column if not exists residence_verify_photo2_url text;
alter table customers add column if not exists residence_verify_photo3_url text;
alter table customers add column if not exists residence_verify_photo4_url text;
alter table guarantors add column if not exists residence_verify_photo2_url text;
alter table guarantors add column if not exists residence_verify_photo3_url text;
alter table guarantors add column if not exists residence_verify_photo4_url text;

/* =====================================================================================
   3. THE SIGNED PAPER CONTRACT -- UP TO TEN PHOTOS, ON THE LOAN.
   =====================================================================================
   "10-photo contract capture + WhatsApp share with autogenerated caption" -- HOPE's loan
   contract is a printed paper document, signed by hand at the field visit; this is not a
   system-generated document (there is no such generator in this codebase, and inventing
   contract wording that customers actually sign is not something to guess at here). What
   the officer captures is a photograph of each signed page, the same live-camera-only
   capture as every other KYC photo. A Postgres array, not ten flat columns -- this is a
   genuinely repeated, undifferentiated set (ten photos of the same kind of thing), unlike
   the business/residence photos above which each mean something different and stay their
   own named column. Capped at 10 client- and server-side. */
alter table loans add column if not exists contract_photo_urls text[];

/* assessments.contract_url and .contract_signed already exist (RUN-ME-001) and were never
   wired to anything -- contract_url now becomes the path of the ONE PDF assembled from the
   captures above at approval (see contractApprovalCleanup in loan-core.js), and
   contract_signed is set true the moment the first contract photo is captured. No new
   columns needed for either. */


/* =====================================================================================
   4. CALL VERIFICATION AT APPROVAL.
   =====================================================================================
   "call verification tick at approval tied to min-seconds threshold from the approver's
   own call-sync login" -- whether the analyst approving this loan actually spoke to the
   customer, read off THEIR OWN synced call log (production call_logs, a different
   database from this sandbox/live split -- see loan-core.js's callVerificationFor_) rather
   than a checkbox anyone could tick. Recorded here so a later reviewer can see what the
   approval screen actually showed, not just today's live call_logs (which are pruned to
   the last two weeks -- see call-core.js). */
alter table assessments add column if not exists call_verified boolean;
alter table assessments add column if not exists call_verified_seconds integer;
alter table assessments add column if not exists call_verified_at timestamptz;

/* =====================================================================================
   5. ASSESSMENT PLAN -- THE PROSPECTIVE-CUSTOMER PLANNER.
   =====================================================================================
   "a new Assessment Plan nav, team-pivoted, only future dates editable, autodelete after
   30 days, autodelete once a matching approved loan appears, dropdown stale-reason
   comments, an ED/elapsed-days column" -- before a customer is even registered, a team
   plans WHO they mean to visit and WHEN, so a manager can see next week filling up rather
   than finding out Friday that nobody has anything booked. Not a loan and not a customer --
   deliberately its own small table, since most of these never become either. */
create table if not exists assessment_plans (
  id uuid primary key default gen_random_uuid(),
  team text not null,
  full_name text not null,
  phone text,
  planned_date date not null,
  stale_reason text,                            -- set once planned_date has passed without a loan; a fixed dropdown, not free text
  created_by text, created_at timestamptz not null default now(),
  updated_by text, updated_at timestamptz not null default now()
);
create index if not exists idx_assessment_plans_team on assessment_plans(team, planned_date);
create index if not exists idx_assessment_plans_phone on assessment_plans(phone);

/* =====================================================================================
   6. GRANT WHAT WAS JUST CREATED -- the belt to RUN-ME-000's braces (see RUN-ME-001 s.14).
   ===================================================================================== */
grant usage on schema hopeloan to postgres, anon, authenticated, service_role;
grant all on all tables    in schema hopeloan to postgres, anon, authenticated, service_role;
grant all on all sequences in schema hopeloan to postgres, anon, authenticated, service_role;

notify pgrst, 'reload schema';
notify pgrst, 'reload config';
