#!/usr/bin/env python3
"""Build the WHITE-ink HOPE wordmark the locked handset shows, straight from the brand file.

    python3 scripts/make-lock-logo.py

WHY THE MARK MATTERS ON THAT PARTICULAR SCREEN
----------------------------------------------------------------------------------------
The lock app is Hoop's signed build -- HOPE runs it on purpose, so that no second APK has to
be downloaded, signed or kept in step (docs/DEVICE-LOCKING.md section 5). Every WORD on the
lock screen already comes from this server, so it reads HOPE. The wordmark did not: it was
compiled into the APK as `R.drawable.hoop_logo_white`, so a locked HOPE handset showed HOOP's
mark sitting directly above the words "HOPE MICROCREDIT".

That is worse than no logo at all. It puts two companies on one screen, in front of the
officer whose phone has just been locked, at the exact moment they are deciding whether this
is their employer or a scam. So the logo became a thing the server sends, like every other
part of that screen, and this is what prepares HOPE's half of it.

WHITE INK, BECAUSE THE GROUND IS ALREADY NAVY
----------------------------------------------------------------------------------------
LockActivity paints 0xFF0B2A6B and puts the mark on it. brand/hope-logo.png is the master:
blue ink (#4530E8) on transparency, drawn for a white ground. Dropped on navy as-is it reads
as a dark smudge -- so the INK is what changes, not the background behind it. A white PNG on
that screen needs no box of its own; it is ink with nothing around it.

DERIVED, NEVER REDRAWN. Same H, same O, same smile curve, every inked pixel turned white with
its alpha untouched -- so the mark on a locked phone can never quietly drift from the brand
file. Anti-aliased edges keep their partial alpha rather than snapping to opaque, which is
what stops the curves going jagged when Android scales the bitmap down.

Everything this writes is CHECKED IN, so neither a deploy nor a bench needs Python. Re-run it
only when brand/hope-logo.png itself changes.
"""
import hashlib
import os

from PIL import Image

SRC = 'brand/hope-logo.png'
# The derived master, checked in beside the source it came from, so the two can be compared.
OUT_SOURCE = 'brand/hope-logo-white.png'
# What the handset actually fetches. public/ is served as written -- no build step (CLAUDE.md).
OUT_PUBLIC = 'public/lock-logo.png'
# The version the beat quotes, generated here so it CANNOT drift from the bytes it names.
OUT_MODULE = 'api/_lib/lock-logo.js'

# The path is relative on purpose: the handset resolves it against the server it was
# provisioned with, so one APK serves both companies and each fetches its own mark.
PUBLIC_PATH = '/lock-logo.png'


def trim(im):
    """Crop away everything transparent or near-white -- both read as 'empty' here. The
    master is ink on transparency, but a copy flattened onto a white square must trim the
    same way, or the mark arrives padded and shows up smaller than everything beside it."""
    im = im.convert('RGBA')
    px = im.load()
    w, h = im.size
    x0, y0, x1, y1 = w, h, -1, -1
    for y in range(h):
        for x in range(w):
            r, g, b, a = px[x, y]
            if a > 24 and not (r > 244 and g > 244 and b > 244):
                if x < x0: x0 = x
                if y < y0: y0 = y
                if x > x1: x1 = x
                if y > y1: y1 = y
    if x1 < 0:
        return im          # nothing inked: hand it back rather than crop to nothing
    return im.crop((x0, y0, x1 + 1, y1 + 1))


def whiten(im):
    """Every inked pixel -> white, alpha untouched. Not a threshold: see the note above."""
    im = im.convert('RGBA')
    _, _, _, a = im.split()
    white = Image.new('L', im.size, 255)
    return Image.merge('RGBA', (white, white, white, a))


def main():
    ink = trim(Image.open(SRC))
    white = whiten(ink)
    print(f'{SRC}: ink is {ink.size[0]}x{ink.size[1]} after trimming, now white')

    for dest in (OUT_SOURCE, OUT_PUBLIC):
        os.makedirs(os.path.dirname(dest), exist_ok=True)
        white.save(dest)
        print(f'  {dest}')

    # SHORT ON PURPOSE. This rides on every beat of every handset, and eight hex characters
    # is already 4 billion to one against two different marks colliding -- a longer one would
    # buy nothing and cost bytes 300 phones pay for, ninety-six times a day.
    version = hashlib.sha256(open(OUT_PUBLIC, 'rb').read()).hexdigest()[:8]
    with open(OUT_MODULE, 'w') as f:
        f.write(f'''/* GENERATED by scripts/make-lock-logo.py -- do not edit by hand.

   The mark a locked handset draws, and the version that tells it when to fetch a new one.
   Generated rather than typed so the version can never name bytes it does not match: a
   stale version is a phone showing last month's logo for ever, with nothing on any screen
   to say so.

   The path is RELATIVE. The handset resolves it against the server it was provisioned
   against, so the same APK serves HOPE and Hoop and each fetches its own mark. */
export const LOCK_LOGO = {{ path: '{PUBLIC_PATH}', version: '{version}' }};
''')
    print(f'  {OUT_MODULE}  (version {version})')


if __name__ == '__main__':
    main()
